---
sources:
# Note the ports listed below will be presented on the remote endpoint as a NAT local port. Do not collide!
- from: 192.0.2.20
  to: 198.18.1.1
  ports:
  - number: 80
    protocol: tcp
  - number: 443
    protocol: tcp
  - number: 162
    protocol: udp
- from: 192.0.2.21
  to: 198.18.1.2
  ports:
  - number: 1812
    protocol: udp
- from: 192.0.2.22
  to: 198.18.1.3
  ports:
  - number: 123
    protocol: udp

destinations:
- to: 203.0.113.20
  as: 198.19.1.1
  ports:
  - number: 22
    protocol: tcp
  - number: 80
    protocol: tcp
  - number: 443
    protocol: tcp
  - number: 161
    protocol: udp
- to: 203.0.113.21
  as: 198.19.1.2
  ports:
  - number: 22
    protocol: tcp
  - number: 80
    protocol: tcp
  - number: 443
    protocol: tcp
  - number: 161
    protocol: udp
