---
sources:
- from: 10.0.2.2
  to: 198.16.0.1

destinations:
- to: 10.0.2.2
  as: 198.17.0.1
  ports:
  - number: 22
    protocol: tcp
  - number: 80
    protocol: tcp
  - number: 443
    protocol: tcp
- to: 10.8.8.6
  as: 198.17.0.2
  ports:
  - number: 22
    protocol: tcp
