---
- hosts: all
  environment:
    http_proxy: http://192.168.1.100:3142
  tasks:
  - include_role:
      name: modules

- hosts: all
  environment:
    http_proxy: http://192.168.1.100:3142
  tasks:
  - include_role:
      name: common
    vars:
    - local_vpn_ip: 192.168.0.20
    - remote_vpn_ip: 192.168.0.10
    - remote_vpn_subnet: 198.18.0.0/16
    - qtun_core_ip: 198.51.100.10
    - local_interface: enp0s8
    - transit_interface: enp0s9
    - vpn_interface: tun0
    - role: remote

#- hosts: all
#  environment:
#    http_proxy: http://192.168.1.100:3142
#  tasks:
#  - include_role:
#      name: inspec

